// Ad-accounts domain: platforms, connections, and statistics.
//
// This is the MOCK implementation. Connections are persisted in localStorage and
// statistics are generated by a seeded PRNG so numbers are stable per account/day
// (no flicker between renders). The seam for real integrations is intentionally
// narrow: replace `connectPlatform` with a real OAuth flow and `getStats` with a
// real reporting-API call — the UI and types stay the same.

export type AdPlatformId = "meta" | "google" | "tiktok";

export interface AdPlatform {
  id: AdPlatformId;
  name: string; // full label, e.g. "Meta Ads"
  short: string; // compact label, e.g. "Meta"
  blurb: string; // one line describing the surface
  color: string; // brand accent used on the platform tile
  glyph: string; // single-char mark for the logo tile
}

export const AD_PLATFORMS: AdPlatform[] = [
  { id: "meta", name: "Meta Ads", short: "Meta", blurb: "Facebook и Instagram", color: "#1877F2", glyph: "f" },
  { id: "google", name: "Google Ads", short: "Google", blurb: "Поиск, YouTube и КМС", color: "#EA4335", glyph: "G" },
  { id: "tiktok", name: "TikTok Ads", short: "TikTok", blurb: "TikTok for Business", color: "#00E0FF", glyph: "♪" },
];

export const PLATFORM_BY_ID = new Map(AD_PLATFORMS.map((p) => [p.id, p]));

export interface AdAccount {
  id: string; // stable key, e.g. "meta:act_5540192"
  platform: AdPlatformId;
  name: string;
  externalId: string; // the platform's own account id
  currency: string;
  status: "active" | "paused";
  connectedAt: string; // ISO
}

// --- Connections (persisted, mock) -----------------------------------------

const LS_KEY = "dw_ad_accounts";

// One canonical demo account per platform, so connecting is idempotent.
const MOCK_ACCOUNT: Record<AdPlatformId, Omit<AdAccount, "connectedAt">> = {
  meta: { id: "meta:act_5540192", platform: "meta", name: "Adspire — Main", externalId: "act_5540192", currency: "USD", status: "active" },
  google: { id: "google:784-221-9930", platform: "google", name: "Adspire — Search", externalId: "784-221-9930", currency: "USD", status: "active" },
  tiktok: { id: "tiktok:70123998812", platform: "tiktok", name: "Adspire — TikTok", externalId: "70123998812", currency: "USD", status: "active" },
};

export function getConnectedAccounts(): AdAccount[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(LS_KEY);
    return raw ? (JSON.parse(raw) as AdAccount[]) : [];
  } catch {
    return [];
  }
}

function save(list: AdAccount[]) {
  try {
    window.localStorage.setItem(LS_KEY, JSON.stringify(list));
  } catch {
    /* ignore quota / private-mode errors */
  }
}

/**
 * Mock "OAuth": add the platform's demo account if not already connected.
 * Real impl would launch the platform OAuth dialog and import the granted
 * accounts. Returns the full updated list.
 */
export function connectPlatform(id: AdPlatformId): AdAccount[] {
  const list = getConnectedAccounts();
  if (!list.some((a) => a.platform === id)) {
    list.push({ ...MOCK_ACCOUNT[id], connectedAt: new Date().toISOString() });
    save(list);
  }
  return list;
}

/**
 * Connect the user's OWN cabinet using the account id they entered in Settings.
 * (The access token is stored in credentials and will authorize real reporting
 * calls once the platform APIs are wired; the connection itself is real per-user.)
 */
export function connectUserAccount(id: AdPlatformId, accountId: string): AdAccount[] {
  const list = getConnectedAccounts();
  const key = `${id}:${accountId}`;
  if (!list.some((a) => a.id === key)) {
    list.push({
      id: key,
      platform: id,
      name: `Кабинет ${accountId}`,
      externalId: accountId,
      currency: "USD",
      status: "active",
      connectedAt: new Date().toISOString(),
    });
    save(list);
  }
  return list;
}

export function disconnectAccount(accountId: string): AdAccount[] {
  const list = getConnectedAccounts().filter((a) => a.id !== accountId);
  save(list);
  return list;
}

export function isPlatformConnected(id: AdPlatformId): boolean {
  return getConnectedAccounts().some((a) => a.platform === id);
}

// --- Statistics (seeded mock) ----------------------------------------------

export interface DayPoint {
  date: string; // YYYY-MM-DD
  spend: number;
  impressions: number;
  clicks: number;
  conversions: number;
}

export interface Kpis {
  spend: number;
  impressions: number;
  clicks: number;
  conversions: number;
  ctr: number; // %
  cpc: number; // $
  cpm: number; // $
  cpa: number; // $
}

export interface Campaign {
  id: string;
  name: string;
  platform: AdPlatformId;
  accountId: string;
  status: "active" | "paused";
  spend: number;
  impressions: number;
  clicks: number;
  ctr: number;
  cpc: number;
  conversions: number;
  cpa: number;
}

export interface StatsResult {
  totals: Kpis;
  deltas: Partial<Record<keyof Kpis, number>>; // % vs previous equal-length period
  series: DayPoint[];
  campaigns: Campaign[];
}

// Deterministic hash + mulberry32 PRNG so a given (account, day) always yields
// the same numbers across renders.
function hash(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) h = Math.imul(h ^ str.charCodeAt(i), 16777619);
  return h >>> 0;
}
function rng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const PLATFORM_SCALE: Record<AdPlatformId, number> = { meta: 1, google: 1.25, tiktok: 0.8 };

// iGaming-flavoured campaign name pool, assigned per platform.
const CAMPAIGN_POOL: Record<AdPlatformId, string[]> = {
  meta: ["Welcome Bonus — Broad", "Free Bet — Retarget", "Slots Lookalike 1%", "Cashback — Winback"],
  google: ["Brand — Search", "Casino — Generic", "App Installs — UAC", "Live Betting — DSA"],
  tiktok: ["Esports — Prospecting", "VIP High Rollers", "Spin & Win — Broad", "Deposit x2 — Retarget"],
};

function isoDay(offsetFromToday: number): string {
  const d = new Date();
  d.setDate(d.getDate() - offsetFromToday);
  return d.toISOString().slice(0, 10);
}

// One day's metrics for one account, seeded by account+date (+ optional campaign).
function dayMetrics(seedKey: string, platform: AdPlatformId) {
  const r = rng(hash(seedKey));
  const scale = PLATFORM_SCALE[platform];
  const impressions = Math.round((18000 + r() * 62000) * scale);
  const ctr = 0.9 + r() * 3.1; // %
  const clicks = Math.round((impressions * ctr) / 100);
  const cpc = 0.18 + r() * 1.35; // $
  const spend = Math.round(clicks * cpc * 100) / 100;
  const cvr = 2 + r() * 6; // %
  const conversions = Math.round((clicks * cvr) / 100);
  return { impressions, clicks, spend, conversions };
}

function emptyKpis(): Kpis {
  return { spend: 0, impressions: 0, clicks: 0, conversions: 0, ctr: 0, cpc: 0, cpm: 0, cpa: 0 };
}

function derive(k: { spend: number; impressions: number; clicks: number; conversions: number }): Kpis {
  return {
    ...k,
    ctr: k.impressions ? (k.clicks / k.impressions) * 100 : 0,
    cpc: k.clicks ? k.spend / k.clicks : 0,
    cpm: k.impressions ? (k.spend / k.impressions) * 1000 : 0,
    cpa: k.conversions ? k.spend / k.conversions : 0,
  };
}

function sumRange(accountIds: string[], platformOf: (id: string) => AdPlatformId, from: number, days: number) {
  const acc = { spend: 0, impressions: 0, clicks: 0, conversions: 0 };
  for (let i = 0; i < days; i++) {
    const date = isoDay(from + i);
    for (const id of accountIds) {
      const m = dayMetrics(`${id}|${date}`, platformOf(id));
      acc.spend += m.spend;
      acc.impressions += m.impressions;
      acc.clicks += m.clicks;
      acc.conversions += m.conversions;
    }
  }
  acc.spend = Math.round(acc.spend * 100) / 100;
  return acc;
}

/**
 * Aggregate statistics for the given accounts over the last `days` days.
 * Real impl would call each platform's reporting API and normalise the rows.
 */
export function getStats(opts: { accounts: AdAccount[]; days: number }): StatsResult {
  const { accounts, days } = opts;
  const ids = accounts.map((a) => a.id);
  const platformOf = (id: string) => accounts.find((a) => a.id === id)!.platform;

  if (!ids.length) {
    return { totals: emptyKpis(), deltas: {}, series: [], campaigns: [] };
  }

  // Daily series (oldest → newest) for the current period.
  const series: DayPoint[] = [];
  for (let i = days - 1; i >= 0; i--) {
    const date = isoDay(i);
    const day = { date, spend: 0, impressions: 0, clicks: 0, conversions: 0 };
    for (const id of ids) {
      const m = dayMetrics(`${id}|${date}`, platformOf(id));
      day.spend += m.spend;
      day.impressions += m.impressions;
      day.clicks += m.clicks;
      day.conversions += m.conversions;
    }
    day.spend = Math.round(day.spend * 100) / 100;
    series.push(day);
  }

  const cur = sumRange(ids, platformOf, 0, days);
  const prev = sumRange(ids, platformOf, days, days);
  const totals = derive(cur);
  const prevK = derive(prev);
  const pct = (a: number, b: number) => (b ? ((a - b) / b) * 100 : 0);
  const deltas: Partial<Record<keyof Kpis, number>> = {
    spend: pct(totals.spend, prevK.spend),
    impressions: pct(totals.impressions, prevK.impressions),
    clicks: pct(totals.clicks, prevK.clicks),
    conversions: pct(totals.conversions, prevK.conversions),
    ctr: pct(totals.ctr, prevK.ctr),
    cpc: pct(totals.cpc, prevK.cpc),
    cpa: pct(totals.cpa, prevK.cpa),
  };

  // Per-campaign aggregation over the same range.
  const campaigns: Campaign[] = [];
  for (const a of accounts) {
    const pool = CAMPAIGN_POOL[a.platform];
    pool.forEach((name, idx) => {
      const cacc = { spend: 0, impressions: 0, clicks: 0, conversions: 0 };
      for (let i = 0; i < days; i++) {
        const date = isoDay(i);
        const m = dayMetrics(`${a.id}|${name}|${date}`, a.platform);
        // Split each account's volume across its campaigns for realism.
        cacc.spend += m.spend / pool.length;
        cacc.impressions += Math.round(m.impressions / pool.length);
        cacc.clicks += Math.round(m.clicks / pool.length);
        cacc.conversions += Math.round(m.conversions / pool.length);
      }
      const d = derive({
        spend: Math.round(cacc.spend * 100) / 100,
        impressions: cacc.impressions,
        clicks: cacc.clicks,
        conversions: cacc.conversions,
      });
      campaigns.push({
        id: `${a.id}|c${idx}`,
        name,
        platform: a.platform,
        accountId: a.id,
        status: idx === pool.length - 1 ? "paused" : "active",
        spend: d.spend,
        impressions: d.impressions,
        clicks: d.clicks,
        ctr: d.ctr,
        cpc: d.cpc,
        conversions: d.conversions,
        cpa: d.cpa,
      });
    });
  }

  return { totals, deltas, series, campaigns };
}

/**
 * Rebuild a single campaign (by its id) plus its daily series, for the drill-down
 * page. Campaign ids are `${accountId}|c${index}`; the account must be connected
 * so we know its platform.
 */
export function getCampaignDetail(
  campaignId: string,
  days: number,
): { campaign: Campaign; series: DayPoint[]; account: AdAccount } | null {
  const marker = campaignId.lastIndexOf("|c");
  if (marker < 0) return null;
  const accountId = campaignId.slice(0, marker);
  const idx = Number.parseInt(campaignId.slice(marker + 2), 10);
  const account = getConnectedAccounts().find((a) => a.id === accountId);
  if (!account || Number.isNaN(idx)) return null;
  const pool = CAMPAIGN_POOL[account.platform];
  const name = pool[idx];
  if (!name) return null;

  const series: DayPoint[] = [];
  const acc = { spend: 0, impressions: 0, clicks: 0, conversions: 0 };
  for (let i = days - 1; i >= 0; i--) {
    const date = isoDay(i);
    const m = dayMetrics(`${accountId}|${name}|${date}`, account.platform);
    const day = {
      date,
      spend: Math.round((m.spend / pool.length) * 100) / 100,
      impressions: Math.round(m.impressions / pool.length),
      clicks: Math.round(m.clicks / pool.length),
      conversions: Math.round(m.conversions / pool.length),
    };
    series.push(day);
    acc.spend += day.spend;
    acc.impressions += day.impressions;
    acc.clicks += day.clicks;
    acc.conversions += day.conversions;
  }
  const d = derive({
    spend: Math.round(acc.spend * 100) / 100,
    impressions: acc.impressions,
    clicks: acc.clicks,
    conversions: acc.conversions,
  });
  const campaign: Campaign = {
    id: campaignId,
    name,
    platform: account.platform,
    accountId,
    status: idx === pool.length - 1 ? "paused" : "active",
    spend: d.spend,
    impressions: d.impressions,
    clicks: d.clicks,
    ctr: d.ctr,
    cpc: d.cpc,
    conversions: d.conversions,
    cpa: d.cpa,
  };
  return { campaign, series, account };
}

// --- Formatting helpers -----------------------------------------------------

export function fmtInt(n: number): string {
  return Math.round(n).toLocaleString("ru-RU");
}
export function fmtMoney(n: number): string {
  return "$" + n.toLocaleString("ru-RU", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
export function fmtPct(n: number): string {
  return n.toFixed(2) + "%";
}
