// Email + mailing domain: email drafts (created in the generator), audiences,
// campaigns and their statistics. MOCK implementation: drafts and user-created
// campaigns persist in localStorage; audiences and baseline campaign stats are
// generated by a seeded PRNG so numbers are stable. The seam for a real ESP
// (SendGrid / Mailgun / etc.) is `sendCampaign` + `getMailOverview`.

export type EmailStyle = "promo" | "newsletter" | "announcement" | "minimal";

export const EMAIL_STYLES: { id: EmailStyle; label: string }[] = [
  { id: "promo", label: "Промо / оффер" },
  { id: "newsletter", label: "Дайджест" },
  { id: "announcement", label: "Анонс" },
  { id: "minimal", label: "Минимал" },
];

export interface EmailDraft {
  id: string;
  name: string;
  subject: string;
  preheader: string;
  brand: string;
  style: EmailStyle;
  accent: string; // hex
  heroTitle: string;
  heroSubtitle: string;
  body: string;
  ctaText: string;
  ctaUrl: string;
  footer: string;
  updatedAt: string; // ISO
}

const DRAFTS_KEY = "dw_email_drafts";

export function newDraft(): EmailDraft {
  return {
    id: "draft_" + Math.random().toString(36).slice(2, 9),
    name: "Новое письмо",
    subject: "🎁 Заберите приветственный бонус 100%",
    preheader: "Только сегодня — удвоим ваш первый депозит",
    brand: "Adspire",
    style: "promo",
    accent: "#7B5CFF",
    heroTitle: "Бонус 100% на первый депозит",
    heroSubtitle: "Плюс 50 фриспинов в любимых слотах",
    body: "Пополните счёт сегодня и получите удвоение суммы, а также фриспины на топовые игры. Предложение ограничено — не упустите момент.",
    ctaText: "Забрать бонус",
    ctaUrl: "https://example.com/bonus",
    footer: "Вы получили письмо, потому что подписаны на рассылку Adspire. Отписаться.",
    updatedAt: new Date().toISOString(),
  };
}

export function getDrafts(): EmailDraft[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(DRAFTS_KEY);
    return raw ? (JSON.parse(raw) as EmailDraft[]) : [];
  } catch {
    return [];
  }
}

function saveDrafts(list: EmailDraft[]) {
  try {
    window.localStorage.setItem(DRAFTS_KEY, JSON.stringify(list));
  } catch {
    /* ignore */
  }
}

/** Upsert a draft by id and return the updated list (newest first). */
export function saveDraft(d: EmailDraft): EmailDraft[] {
  const list = getDrafts().filter((x) => x.id !== d.id);
  list.unshift({ ...d, updatedAt: new Date().toISOString() });
  saveDrafts(list);
  return list;
}

export function deleteDraft(id: string): EmailDraft[] {
  const list = getDrafts().filter((x) => x.id !== id);
  saveDrafts(list);
  return list;
}

// --- Audiences (static mock) -----------------------------------------------

export interface Audience {
  id: string;
  name: string;
  count: number;
}

export const AUDIENCES: Audience[] = [
  { id: "all", name: "Все подписчики", count: 48213 },
  { id: "vip", name: "VIP-игроки", count: 3912 },
  { id: "depositors", name: "Депозиторы", count: 9330 },
  { id: "inactive", name: "Неактивные 30 дней", count: 12004 },
  { id: "new", name: "Новые (7 дней)", count: 2140 },
];

export const AUDIENCE_BY_ID = new Map(AUDIENCES.map((a) => [a.id, a]));

// --- Campaigns -------------------------------------------------------------

export type CampaignStatus = "draft" | "scheduled" | "sent";

export interface MailCampaign {
  id: string;
  name: string;
  subject: string;
  audienceId: string;
  status: CampaignStatus;
  recipients: number;
  sentAt?: string; // ISO date
  scheduledAt?: string; // local datetime string when status === "scheduled"
  // Delivery stats (meaningful once sent).
  delivered: number;
  opens: number;
  clicks: number;
  unsub: number;
  bounce: number;
}

const CAMPAIGNS_KEY = "dw_mail_campaigns";

function hash(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) h = Math.imul(h ^ str.charCodeAt(i), 16777619);
  return h >>> 0;
}
function rng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function isoDay(offset: number): string {
  const d = new Date();
  d.setDate(d.getDate() - offset);
  return d.toISOString().slice(0, 10);
}

// Fill delivery stats for a sent campaign, seeded by id so they never flicker.
function seedSentStats(id: string, recipients: number): Pick<MailCampaign, "delivered" | "opens" | "clicks" | "unsub" | "bounce"> {
  const r = rng(hash(id));
  const bounceRate = 0.005 + r() * 0.02;
  const delivered = Math.round(recipients * (1 - bounceRate));
  const openRate = 0.18 + r() * 0.32; // 18–50%
  const opens = Math.round(delivered * openRate);
  const ctor = 0.06 + r() * 0.16; // click-to-open
  const clicks = Math.round(opens * ctor);
  const unsub = Math.round(delivered * (0.001 + r() * 0.004));
  const bounce = recipients - delivered;
  return { delivered, opens, clicks, unsub, bounce };
}

// A few baseline "sent" campaigns so the cabinet isn't empty on first visit.
const BASE_CAMPAIGNS: MailCampaign[] = [
  { seed: "Приветственный бонус — Все", audienceId: "all", dayAgo: 2, name: "Приветственный бонус 100%" },
  { seed: "VIP кэшбэк — VIP", audienceId: "vip", dayAgo: 5, name: "VIP-кэшбэк недели" },
  { seed: "Реактивация — Неактивные", audienceId: "inactive", dayAgo: 9, name: "Мы скучали — 30 фриспинов" },
  { seed: "Депозит x2 — Депозиторы", audienceId: "depositors", dayAgo: 14, name: "Депозит x2 в выходные" },
].map((c) => {
  const aud = AUDIENCE_BY_ID.get(c.audienceId)!;
  const stats = seedSentStats(c.seed, aud.count);
  return {
    id: "base_" + hash(c.seed).toString(36),
    name: c.name,
    subject: c.name,
    audienceId: c.audienceId,
    status: "sent" as CampaignStatus,
    recipients: aud.count,
    sentAt: isoDay(c.dayAgo),
    ...stats,
  };
});

function getUserCampaigns(): MailCampaign[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(CAMPAIGNS_KEY);
    return raw ? (JSON.parse(raw) as MailCampaign[]) : [];
  } catch {
    return [];
  }
}
function saveUserCampaigns(list: MailCampaign[]) {
  try {
    window.localStorage.setItem(CAMPAIGNS_KEY, JSON.stringify(list));
  } catch {
    /* ignore */
  }
}

/** All campaigns: user-created (newest first) + the baseline demo set. */
export function getCampaigns(): MailCampaign[] {
  return [...getUserCampaigns(), ...BASE_CAMPAIGNS];
}

/**
 * Mock "send": create a campaign from a draft + audience and mark it sent with
 * seeded delivery stats. Real impl would enqueue the send with the ESP.
 */
export function sendCampaign(opts: { draft: EmailDraft; audienceId: string }): MailCampaign {
  const aud = AUDIENCE_BY_ID.get(opts.audienceId) ?? AUDIENCES[0];
  const id = "c_" + Math.random().toString(36).slice(2, 9);
  const stats = seedSentStats(id, aud.count);
  const campaign: MailCampaign = {
    id,
    name: opts.draft.name,
    subject: opts.draft.subject,
    audienceId: aud.id,
    status: "sent",
    recipients: aud.count,
    sentAt: isoDay(0),
    ...stats,
  };
  saveUserCampaigns([campaign, ...getUserCampaigns()]);
  return campaign;
}

/**
 * Schedule a campaign for a future datetime. It sits as "scheduled" until its
 * time passes, then `processDueCampaigns` flips it to "sent" with delivery stats.
 */
export function scheduleCampaign(opts: {
  draft: EmailDraft;
  audienceId: string;
  scheduledAt: string;
}): MailCampaign {
  const aud = AUDIENCE_BY_ID.get(opts.audienceId) ?? AUDIENCES[0];
  const id = "c_" + Math.random().toString(36).slice(2, 9);
  const campaign: MailCampaign = {
    id,
    name: opts.draft.name,
    subject: opts.draft.subject,
    audienceId: aud.id,
    status: "scheduled",
    recipients: aud.count,
    scheduledAt: opts.scheduledAt,
    delivered: 0,
    opens: 0,
    clicks: 0,
    unsub: 0,
    bounce: 0,
  };
  saveUserCampaigns([campaign, ...getUserCampaigns()]);
  return campaign;
}

/** Flip any scheduled campaign whose time has passed to "sent" with stats. */
export function processDueCampaigns(): void {
  const now = Date.now();
  const list = getUserCampaigns();
  let changed = false;
  for (const c of list) {
    if (c.status === "scheduled" && c.scheduledAt && new Date(c.scheduledAt).getTime() <= now) {
      Object.assign(c, seedSentStats(c.id, c.recipients));
      c.status = "sent";
      c.sentAt = c.scheduledAt.slice(0, 10);
      changed = true;
    }
  }
  if (changed) saveUserCampaigns(list);
}

// --- Overview stats --------------------------------------------------------

export interface MailKpis {
  sent: number;
  delivered: number;
  opens: number;
  clicks: number;
  openRate: number; // %
  ctr: number; // % (clicks / delivered)
  unsub: number;
  bounce: number;
}

export interface MailOverview {
  totals: MailKpis;
  series: { date: string; opens: number; clicks: number }[];
}

export function getMailOverview(days: number): MailOverview {
  const sent = getCampaigns().filter((c) => c.status === "sent");
  const agg = { sent: 0, delivered: 0, opens: 0, clicks: 0, unsub: 0, bounce: 0 };
  for (const c of sent) {
    agg.sent += c.recipients;
    agg.delivered += c.delivered;
    agg.opens += c.opens;
    agg.clicks += c.clicks;
    agg.unsub += c.unsub;
    agg.bounce += c.bounce;
  }
  const totals: MailKpis = {
    ...agg,
    openRate: agg.delivered ? (agg.opens / agg.delivered) * 100 : 0,
    ctr: agg.delivered ? (agg.clicks / agg.delivered) * 100 : 0,
  };

  // Seeded daily opens/clicks so the trend chart has shape.
  const series: MailOverview["series"] = [];
  const base = Math.max(1, Math.round(agg.opens / days));
  for (let i = days - 1; i >= 0; i--) {
    const date = isoDay(i);
    const r = rng(hash("mail|" + date));
    const opens = Math.round(base * (0.55 + r() * 0.9));
    const clicks = Math.round(opens * (0.08 + r() * 0.14));
    series.push({ date, opens, clicks });
  }
  return { totals, series };
}

// --- Formatting ------------------------------------------------------------

export function fmtInt(n: number): string {
  return Math.round(n).toLocaleString("ru-RU");
}
export function fmtPct(n: number): string {
  return n.toFixed(1) + "%";
}
