// Email + mailing domain: email drafts (created in the generator), audiences,
// campaigns and their statistics. MOCK implementation: drafts and user-created
// campaigns persist in localStorage; audiences and baseline campaign stats are
// generated by a seeded PRNG so numbers are stable. The seam for a real ESP
// (SendGrid / Mailgun / etc.) is `sendCampaign` + `getMailOverview`.

import { DEFAULT_EMAIL_ACCENT, DEFAULT_EMAIL_BASE, LEGACY_LIGHT_BASE, isHex } from "./emailPalette";

export type EmailStyle = "promo" | "newsletter" | "announcement" | "minimal";

export const EMAIL_STYLES: { id: EmailStyle; label: string }[] = [
  { id: "promo", label: "Промо / оффер" },
  { id: "newsletter", label: "Дайджест" },
  { id: "announcement", label: "Анонс" },
  { id: "minimal", label: "Минимал" },
];

/**
 * Необязательные блоки письма. Раньше блок появлялся, если в его поле что-то
 * написали, — то есть состав письма нельзя было задать, он выводился из
 * заполненности. Теперь это отдельный выключатель: пустой блок можно оставить
 * включённым и дописать позже, а заполненный — выключить, не стирая текст.
 */
export type EmailBlockId =
  | "hero"
  | "subtitle"
  | "body"
  | "steps"
  | "cta"
  | "bonusCta"
  | "apps"
  | "payments"
  | "footer";

export type EmailBlocks = Record<EmailBlockId, boolean>;

export const EMAIL_BLOCKS: { id: EmailBlockId; label: string; hint: string }[] = [
  { id: "hero", label: "Шапка", hint: "Баннер или полоса с брендом" },
  { id: "subtitle", label: "Подзаголовок", hint: "Строка под заголовком" },
  { id: "body", label: "Текст письма", hint: "Основной абзац" },
  { id: "steps", label: "Шаги активации", hint: "Нумерованный список" },
  { id: "cta", label: "Кнопка сверху", hint: "Сразу под заголовком" },
  { id: "bonusCta", label: "Кнопка снизу", hint: "Повтор после текста" },
  { id: "apps", label: "Мобильное приложение", hint: "App Store и Google Play" },
  { id: "payments", label: "Платёжные системы", hint: "Ряд логотипов" },
  { id: "footer", label: "Футер", hint: "Дисклеймер и отписка" },
];

export const EMAIL_BLOCK_DEFAULTS: EmailBlocks = {
  hero: true,
  subtitle: true,
  body: true,
  steps: true,
  cta: true,
  // Вторая кнопка — повтор первой, в большинстве писем она лишняя.
  bonusCta: false,
  apps: true,
  payments: true,
  footer: true,
};

/**
 * База гаммы черновика. У старых черновиков её нет — берём цвет по бывшему
 * флагу темы, чтобы сохранённое письмо не поменяло вид само по себе.
 */
export function emailBase(draft: Pick<EmailDraft, "base" | "dark">): string {
  if (isHex(draft.base)) return draft.base;
  return draft.dark === false ? LEGACY_LIGHT_BASE : DEFAULT_EMAIL_BASE;
}

/** Черновик из прошлой версии не знал про blocks и гамму — добираем. */
export function withBlocks(draft: EmailDraft): EmailDraft {
  return {
    ...draft,
    accent: isHex(draft.accent) ? draft.accent : DEFAULT_EMAIL_ACCENT,
    base: emailBase(draft),
    blocks: { ...EMAIL_BLOCK_DEFAULTS, ...(draft.blocks ?? {}) },
  };
}

/**
 * Внутреннее имя письма — латиница без пробелов. Оно становится именем файла
 * при выгрузке и именем кампании при отправке, а эти имена уезжают на почтовые
 * сервисы и файловые хранилища, где кириллица и пробелы превращаются в
 * %D0%BF%D0%B8 и ломают ссылки.
 */
const TRANSLIT: Record<string, string> = {
  а: "a", б: "b", в: "v", г: "g", д: "d", е: "e", ё: "e", ж: "zh", з: "z",
  и: "i", й: "y", к: "k", л: "l", м: "m", н: "n", о: "o", п: "p", р: "r",
  с: "s", т: "t", у: "u", ф: "f", х: "h", ц: "c", ч: "ch", ш: "sh", щ: "sch",
  ъ: "", ы: "y", ь: "", э: "e", ю: "yu", я: "ya",
  // Украинские и белорусские буквы: те же письма верстаются и на них.
  і: "i", ї: "yi", є: "ye", ґ: "g", ў: "u",
};

function translit(s: string): string {
  return s
    .toLowerCase()
    .split("")
    .map((ch) => (ch in TRANSLIT ? TRANSLIT[ch] : ch))
    .join("");
}

/**
 * Привести введённое имя к латинице без пробелов. Хвостовой дефис не срезаем:
 * человек печатает, и слово, которое он ещё не дописал, не должно прыгать.
 */
export function sanitizeEmailName(raw: string): string {
  return translit(raw)
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/-{2,}/g, "-")
    .replace(/^-+/, "")
    .slice(0, 60);
}

/** Имя, которое подставляется из темы письма. */
export function emailNameFromSubject(subject: string): string {
  return sanitizeEmailName(subject).replace(/-+$/, "");
}

export interface EmailDraft {
  id: string;
  name: string;
  subject: string;
  preheader: string;
  brand: string;
  brandMode: "text" | "logo";
  style: EmailStyle;
  accent: string;
  /** Базовый цвет гаммы: от него считается фон, полотно, текст и разделители. */
  base: string;
  /**
   * Легаси: до гаммы тема была переключателем на два зашитых набора цветов.
   * Поле осталось только для чтения старых черновиков — см. `emailBase`.
   */
  dark?: boolean;
  heroImage: string;
  logo: string;
  logoMode: "reference" | "overlay";
  heroTitle: string;
  heroSubtitle: string;
  body: string;
  steps: string[];
  ctaText: string;
  ctaUrl: string;
  bonusCtaText: string;
  footer: string;
  unsubscribeUrl: string;
  /** Какие необязательные блоки входят в письмо. */
  blocks: EmailBlocks;
  updatedAt: string;
}

const DRAFTS_KEY = "dw_email_drafts";

export function newDraft(): EmailDraft {
  return {
    id: "draft_" + Math.random().toString(36).slice(2, 9),
    name: "",
    subject: "",
    preheader: "",
    brand: "",
    brandMode: "text",
    style: "promo",
    accent: DEFAULT_EMAIL_ACCENT,
    base: DEFAULT_EMAIL_BASE,
    heroImage: "",
    logo: "",
    logoMode: "reference",
    heroTitle: "",
    heroSubtitle: "",
    body: "",
    steps: ["", "", ""],
    ctaText: "",
    ctaUrl: "",
    bonusCtaText: "",
    footer: "",
    unsubscribeUrl: "",
    blocks: { ...EMAIL_BLOCK_DEFAULTS },
    updatedAt: new Date().toISOString(),
  };
}

export function sampleDraft(id: string): EmailDraft {
  return {
    id,
    name: "promo-50-freespins",
    subject: "50 фриспинов + бонус 100% на депозит",
    preheader: "Только до конца недели — заряжайте удочки!",
    brand: "20BET",
    brandMode: "text",
    style: "promo",
    accent: DEFAULT_EMAIL_ACCENT,
    base: DEFAULT_EMAIL_BASE,
    heroImage: "",
    logo: "",
    logoMode: "reference",
    heroTitle: "50 ФРИСПИНОВ BIG BASS BLAST + БОНУС **100% ДО 50 EUR**",
    heroSubtitle: "",
    body: "Лучшие слоты нашей коллекции ещё интереснее с бонусом! На этой неделе — **100% буст** и 50 фриспинов в слоте **Big Bass Blast** от **Pragmatic Play**. Внесите депозит от **20 EUR** до конца недели и активируйте бонус.",
    steps: [
      "Выберите карточку бонуса при пополнении счёта",
      "Сделайте депозит от **20 EUR**",
      "Получите 50 фриспинов + бонус **100% до 50 EUR**",
    ],
    ctaText: "PLAY NOW",
    ctaUrl: "https://example.com/play",
    bonusCtaText: "GET BONUS",
    footer: "Это автоматическое сообщение, отвечать не нужно.",
    unsubscribeUrl: "https://example.com/unsubscribe",
    blocks: { ...EMAIL_BLOCK_DEFAULTS, bonusCta: true },
    updatedAt: new Date().toISOString(),
  };
}

export function getDrafts(): EmailDraft[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(DRAFTS_KEY);
    // Черновики, сохранённые до появления настройки состава, приходят без
    // blocks — добираем умолчаниями, иначе письмо соберётся пустым.
    return raw ? (JSON.parse(raw) as EmailDraft[]).map(withBlocks) : [];
  } catch {
    return [];
  }
}

function saveDrafts(list: EmailDraft[]) {
  try {
    window.localStorage.setItem(DRAFTS_KEY, JSON.stringify(list));
  } catch {
    /* ignore */
  }
}

/** Upsert a draft by id and return the updated list (newest first). */
export function saveDraft(d: EmailDraft): EmailDraft[] {
  const list = getDrafts().filter((x) => x.id !== d.id);
  list.unshift({ ...d, updatedAt: new Date().toISOString() });
  saveDrafts(list);
  return list;
}

export function deleteDraft(id: string): EmailDraft[] {
  const list = getDrafts().filter((x) => x.id !== id);
  saveDrafts(list);
  return list;
}

export interface Audience {
  id: string;
  name: string;
  count: number;
}

export const AUDIENCES: Audience[] = [
  { id: "all", name: "Все подписчики", count: 48213 },
  { id: "vip", name: "VIP-игроки", count: 3912 },
  { id: "depositors", name: "Депозиторы", count: 9330 },
  { id: "inactive", name: "Неактивные 30 дней", count: 12004 },
  { id: "new", name: "Новые (7 дней)", count: 2140 },
];

export const AUDIENCE_BY_ID = new Map(AUDIENCES.map((a) => [a.id, a]));

export type CampaignStatus = "draft" | "scheduled" | "sent";

export interface MailCampaign {
  id: string;
  name: string;
  subject: string;
  audienceId: string;
  status: CampaignStatus;
  recipients: number;
  sentAt?: string;
  scheduledAt?: string;
  delivered: number;
  opens: number;
  clicks: number;
  unsub: number;
  bounce: number;
}

const CAMPAIGNS_KEY = "dw_mail_campaigns";

function hash(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) h = Math.imul(h ^ str.charCodeAt(i), 16777619);
  return h >>> 0;
}
function rng(seed: number) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function isoDay(offset: number): string {
  const d = new Date();
  d.setDate(d.getDate() - offset);
  return d.toISOString().slice(0, 10);
}

// Fill delivery stats for a sent campaign, seeded by id so they never flicker.
function seedSentStats(id: string, recipients: number): Pick<MailCampaign, "delivered" | "opens" | "clicks" | "unsub" | "bounce"> {
  const r = rng(hash(id));
  const bounceRate = 0.005 + r() * 0.02;
  const delivered = Math.round(recipients * (1 - bounceRate));
  const openRate = 0.18 + r() * 0.32;
  const opens = Math.round(delivered * openRate);
  const ctor = 0.06 + r() * 0.16;
  const clicks = Math.round(opens * ctor);
  const unsub = Math.round(delivered * (0.001 + r() * 0.004));
  const bounce = recipients - delivered;
  return { delivered, opens, clicks, unsub, bounce };
}

const BASE_CAMPAIGNS: MailCampaign[] = [
  { seed: "Приветственный бонус — Все", audienceId: "all", dayAgo: 2, name: "Приветственный бонус 100%" },
  { seed: "VIP кэшбэк — VIP", audienceId: "vip", dayAgo: 5, name: "VIP-кэшбэк недели" },
  { seed: "Реактивация — Неактивные", audienceId: "inactive", dayAgo: 9, name: "Мы скучали — 30 фриспинов" },
  { seed: "Депозит x2 — Депозиторы", audienceId: "depositors", dayAgo: 14, name: "Депозит x2 в выходные" },
].map((c) => {
  const aud = AUDIENCE_BY_ID.get(c.audienceId)!;
  const stats = seedSentStats(c.seed, aud.count);
  return {
    id: "base_" + hash(c.seed).toString(36),
    name: c.name,
    subject: c.name,
    audienceId: c.audienceId,
    status: "sent" as CampaignStatus,
    recipients: aud.count,
    sentAt: isoDay(c.dayAgo),
    ...stats,
  };
});

function getUserCampaigns(): MailCampaign[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(CAMPAIGNS_KEY);
    return raw ? (JSON.parse(raw) as MailCampaign[]) : [];
  } catch {
    return [];
  }
}
function saveUserCampaigns(list: MailCampaign[]) {
  try {
    window.localStorage.setItem(CAMPAIGNS_KEY, JSON.stringify(list));
  } catch {
    /* ignore */
  }
}

/** All campaigns: user-created (newest first) + the baseline demo set. */
export function getCampaigns(): MailCampaign[] {
  return [...getUserCampaigns(), ...BASE_CAMPAIGNS];
}

/**
 * Mock "send": create a campaign from a draft + audience and mark it sent with
 * seeded delivery stats. Real impl would enqueue the send with the ESP.
 */
export function sendCampaign(opts: { draft: EmailDraft; audienceId: string }): MailCampaign {
  const aud = AUDIENCE_BY_ID.get(opts.audienceId) ?? AUDIENCES[0];
  const id = "c_" + Math.random().toString(36).slice(2, 9);
  const stats = seedSentStats(id, aud.count);
  const campaign: MailCampaign = {
    id,
    name: opts.draft.name,
    subject: opts.draft.subject,
    audienceId: aud.id,
    status: "sent",
    recipients: aud.count,
    sentAt: isoDay(0),
    ...stats,
  };
  saveUserCampaigns([campaign, ...getUserCampaigns()]);
  return campaign;
}

/**
 * Schedule a campaign for a future datetime. It sits as "scheduled" until its
 * time passes, then `processDueCampaigns` flips it to "sent" with delivery stats.
 */
export function scheduleCampaign(opts: {
  draft: EmailDraft;
  audienceId: string;
  scheduledAt: string;
}): MailCampaign {
  const aud = AUDIENCE_BY_ID.get(opts.audienceId) ?? AUDIENCES[0];
  const id = "c_" + Math.random().toString(36).slice(2, 9);
  const campaign: MailCampaign = {
    id,
    name: opts.draft.name,
    subject: opts.draft.subject,
    audienceId: aud.id,
    status: "scheduled",
    recipients: aud.count,
    scheduledAt: opts.scheduledAt,
    delivered: 0,
    opens: 0,
    clicks: 0,
    unsub: 0,
    bounce: 0,
  };
  saveUserCampaigns([campaign, ...getUserCampaigns()]);
  return campaign;
}

/** Flip any scheduled campaign whose time has passed to "sent" with stats. */
export function processDueCampaigns(): void {
  const now = Date.now();
  const list = getUserCampaigns();
  let changed = false;
  for (const c of list) {
    if (c.status === "scheduled" && c.scheduledAt && new Date(c.scheduledAt).getTime() <= now) {
      Object.assign(c, seedSentStats(c.id, c.recipients));
      c.status = "sent";
      c.sentAt = c.scheduledAt.slice(0, 10);
      changed = true;
    }
  }
  if (changed) saveUserCampaigns(list);
}

export interface MailKpis {
  sent: number;
  delivered: number;
  opens: number;
  clicks: number;
  openRate: number;
  ctr: number;
  unsub: number;
  bounce: number;
}

export interface MailOverview {
  totals: MailKpis;
  series: { date: string; opens: number; clicks: number }[];
}

export function getMailOverview(days: number): MailOverview {
  const sent = getCampaigns().filter((c) => c.status === "sent");
  const agg = { sent: 0, delivered: 0, opens: 0, clicks: 0, unsub: 0, bounce: 0 };
  for (const c of sent) {
    agg.sent += c.recipients;
    agg.delivered += c.delivered;
    agg.opens += c.opens;
    agg.clicks += c.clicks;
    agg.unsub += c.unsub;
    agg.bounce += c.bounce;
  }
  const totals: MailKpis = {
    ...agg,
    openRate: agg.delivered ? (agg.opens / agg.delivered) * 100 : 0,
    ctr: agg.delivered ? (agg.clicks / agg.delivered) * 100 : 0,
  };

  const series: MailOverview["series"] = [];
  const base = Math.max(1, Math.round(agg.opens / days));
  for (let i = days - 1; i >= 0; i--) {
    const date = isoDay(i);
    const r = rng(hash("mail|" + date));
    const opens = Math.round(base * (0.55 + r() * 0.9));
    const clicks = Math.round(opens * (0.08 + r() * 0.14));
    series.push({ date, opens, clicks });
  }
  return { totals, series };
}

export function fmtInt(n: number): string {
  return Math.round(n).toLocaleString("ru-RU");
}
export function fmtPct(n: number): string {
  return n.toFixed(1) + "%";
}
