-- =====================================================================
-- «Чужие» таблицы (не Dream Weaver) — оценщик / чат / бенчмарки.
-- Схема выведена из заголовков и данных CSV-экспортов, типы —
-- обоснованное предположение. Если у вас есть оригинальный DDL из
-- репозитория того приложения — используйте его вместо этого файла.
--
-- Запускать в НОВОМ проекте Supabase: Dashboard -> SQL Editor -> Run.
-- Идемпотентно (create table if not exists). RLS включён и БЕЗ политик
-- => доступ только через service_role. Если то приложение читает через
-- anon/authenticated — добавьте нужные policy (см. блок в конце).
-- =====================================================================

-- ---------------------------------------------------------------------
-- chat_sessions — сессии чат-ассистента (conversation_id + messages jsonb)
-- CSV: id,conversation_id,messages,created_at,updated_at
-- ---------------------------------------------------------------------
create table if not exists public.chat_sessions (
  id              bigint primary key generated by default as identity,
  conversation_id text not null,
  messages        jsonb,                         -- массив сообщений (в экспорте — JSON-строка)
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);
create index if not exists chat_sessions_conversation_idx
  on public.chat_sessions (conversation_id);

-- ---------------------------------------------------------------------
-- estimations — справочник тиров оценки по типам услуг
-- CSV: id,service_type,competency,hours_min,hours_max,notes,questions,created_at,tier_key
-- ---------------------------------------------------------------------
create table if not exists public.estimations (
  id          bigint primary key generated by default as identity,
  service_type text not null,
  competency  text,
  hours_min   integer,
  hours_max   integer,
  notes       text,
  questions   jsonb,                             -- массив вопросов
  created_at  timestamptz default now(),
  tier_key    text
);
create index if not exists estimations_service_idx
  on public.estimations (service_type);

-- ---------------------------------------------------------------------
-- estimations_history — история задач/оценок (PK = task_id, текстовый ClickUp id)
-- CSV: task_id,service_type,client,name,status,new_or_revision,min_h,max_h,
--      time_spent_h,created_at,updated_at,closed_at,lang,brief,comments,attachments,url
-- ---------------------------------------------------------------------
create table if not exists public.estimations_history (
  task_id         text primary key,
  service_type    text,
  client          text,
  name            text,
  status          text,
  new_or_revision text,
  min_h           integer,
  max_h           integer,
  time_spent_h    numeric,
  created_at      timestamptz,
  updated_at      timestamptz,
  closed_at       timestamptz,
  lang            text,
  brief           text,
  comments        text,
  attachments     text,
  url             text
);
create index if not exists estimations_history_service_idx
  on public.estimations_history (service_type);
create index if not exists estimations_history_status_idx
  on public.estimations_history (status);

-- ---------------------------------------------------------------------
-- market_benchmarks — рыночные ориентиры по метрикам услуг
-- CSV: id,service_type,metric,unit,v_min,v_avg,v_max,v_median,sources,updated_at
-- ---------------------------------------------------------------------
create table if not exists public.market_benchmarks (
  id           bigint primary key generated by default as identity,
  service_type text not null,
  metric       text not null,
  unit         text,
  v_min        numeric,
  v_avg        numeric,
  v_max        numeric,
  v_median     numeric,
  sources      jsonb,                            -- [{url,name}, ...]
  updated_at   timestamptz default now()
);
create index if not exists market_benchmarks_service_idx
  on public.market_benchmarks (service_type, metric);

-- ---------------------------------------------------------------------
-- RLS: включаем, политик нет => через PostgREST (anon/authenticated)
-- доступа НЕТ, работает только service_role. Раскомментируйте нужное,
-- если то приложение обращается к таблицам клиентским ключом.
-- ---------------------------------------------------------------------
alter table public.chat_sessions        enable row level security;
alter table public.estimations          enable row level security;
alter table public.estimations_history  enable row level security;
alter table public.market_benchmarks    enable row level security;

-- Пример: публичное чтение справочников (если нужно фронту напрямую):
-- create policy estimations_read on public.estimations
--   for select using (auth.role() = 'authenticated');
-- create policy benchmarks_read on public.market_benchmarks
--   for select using (auth.role() = 'authenticated');

-- ---------------------------------------------------------------------
-- ПОСЛЕ импорта данных с явными id — сбросить identity-счётчики,
-- иначе следующая авто-вставка столкнётся с существующим id.
-- (Запускать после \copy / CSV import. Для estimations_history не нужно —
--  там текстовый PK.)
-- ---------------------------------------------------------------------
-- select setval(pg_get_serial_sequence('public.chat_sessions','id'),     coalesce((select max(id) from public.chat_sessions), 1));
-- select setval(pg_get_serial_sequence('public.estimations','id'),       coalesce((select max(id) from public.estimations), 1));
-- select setval(pg_get_serial_sequence('public.market_benchmarks','id'), coalesce((select max(id) from public.market_benchmarks), 1));
