/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as HistoryCardIdRouteImport } from './routes/history/$cardId'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiFetchMasterRouteImport } from './routes/api/fetch-master'
import { Route as ApiExtractMasterRouteImport } from './routes/api/extract-master'
import { Route as ApiHistoryIndexRouteImport } from './routes/api/history/index'
import { Route as ApiHistoryUploadStatusRouteImport } from './routes/api/history/upload-status'
import { Route as ApiHistoryRestoreRouteImport } from './routes/api/history/restore'
import { Route as ApiHistoryCloneCardRouteImport } from './routes/api/history/clone-card'
import { Route as ApiHistoryBulkZipRouteImport } from './routes/api/history/bulk-zip'
import { Route as ApiHistoryBulkDeleteRouteImport } from './routes/api/history/bulk-delete'
import { Route as ApiHistoryCardIdRouteImport } from './routes/api/history/$cardId'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAdminRoleRouteImport } from './routes/api/admin/role'
import { Route as ApiAdminPricingRouteImport } from './routes/api/admin/pricing'
import { Route as ApiAdminLogsRouteImport } from './routes/api/admin/logs'
import { Route as ApiAdminHistoryRouteImport } from './routes/api/admin/history'
import { Route as ApiAdminCreditsRouteImport } from './routes/api/admin/credits'
import { Route as ApiHistoryCardIdResizeTileRouteImport } from './routes/api/history/$cardId.resize-tile'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryCardIdRoute = HistoryCardIdRouteImport.update({
  id: '/history/$cardId',
  path: '/history/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchMasterRoute = ApiFetchMasterRouteImport.update({
  id: '/api/fetch-master',
  path: '/api/fetch-master',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractMasterRoute = ApiExtractMasterRouteImport.update({
  id: '/api/extract-master',
  path: '/api/extract-master',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryIndexRoute = ApiHistoryIndexRouteImport.update({
  id: '/api/history/',
  path: '/api/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryUploadStatusRoute = ApiHistoryUploadStatusRouteImport.update({
  id: '/api/history/upload-status',
  path: '/api/history/upload-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRestoreRoute = ApiHistoryRestoreRouteImport.update({
  id: '/api/history/restore',
  path: '/api/history/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryCloneCardRoute = ApiHistoryCloneCardRouteImport.update({
  id: '/api/history/clone-card',
  path: '/api/history/clone-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryBulkZipRoute = ApiHistoryBulkZipRouteImport.update({
  id: '/api/history/bulk-zip',
  path: '/api/history/bulk-zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryBulkDeleteRoute = ApiHistoryBulkDeleteRouteImport.update({
  id: '/api/history/bulk-delete',
  path: '/api/history/bulk-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryCardIdRoute = ApiHistoryCardIdRouteImport.update({
  id: '/api/history/$cardId',
  path: '/api/history/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoleRoute = ApiAdminRoleRouteImport.update({
  id: '/api/admin/role',
  path: '/api/admin/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPricingRoute = ApiAdminPricingRouteImport.update({
  id: '/api/admin/pricing',
  path: '/api/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogsRoute = ApiAdminLogsRouteImport.update({
  id: '/api/admin/logs',
  path: '/api/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminHistoryRoute = ApiAdminHistoryRouteImport.update({
  id: '/api/admin/history',
  path: '/api/admin/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreditsRoute = ApiAdminCreditsRouteImport.update({
  id: '/api/admin/credits',
  path: '/api/admin/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryCardIdResizeTileRoute =
  ApiHistoryCardIdResizeTileRouteImport.update({
    id: '/resize-tile',
    path: '/resize-tile',
    getParentRoute: () => ApiHistoryCardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/extract-master': typeof ApiExtractMasterRoute
  '/api/fetch-master': typeof ApiFetchMasterRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/me': typeof ApiMeRoute
  '/history/$cardId': typeof HistoryCardIdRoute
  '/history/': typeof HistoryIndexRoute
  '/api/admin/credits': typeof ApiAdminCreditsRoute
  '/api/admin/history': typeof ApiAdminHistoryRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/admin/role': typeof ApiAdminRoleRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/history/$cardId': typeof ApiHistoryCardIdRouteWithChildren
  '/api/history/bulk-delete': typeof ApiHistoryBulkDeleteRoute
  '/api/history/bulk-zip': typeof ApiHistoryBulkZipRoute
  '/api/history/clone-card': typeof ApiHistoryCloneCardRoute
  '/api/history/restore': typeof ApiHistoryRestoreRoute
  '/api/history/upload-status': typeof ApiHistoryUploadStatusRoute
  '/api/history/': typeof ApiHistoryIndexRoute
  '/api/history/$cardId/resize-tile': typeof ApiHistoryCardIdResizeTileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/extract-master': typeof ApiExtractMasterRoute
  '/api/fetch-master': typeof ApiFetchMasterRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/me': typeof ApiMeRoute
  '/history/$cardId': typeof HistoryCardIdRoute
  '/history': typeof HistoryIndexRoute
  '/api/admin/credits': typeof ApiAdminCreditsRoute
  '/api/admin/history': typeof ApiAdminHistoryRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/admin/role': typeof ApiAdminRoleRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/history/$cardId': typeof ApiHistoryCardIdRouteWithChildren
  '/api/history/bulk-delete': typeof ApiHistoryBulkDeleteRoute
  '/api/history/bulk-zip': typeof ApiHistoryBulkZipRoute
  '/api/history/clone-card': typeof ApiHistoryCloneCardRoute
  '/api/history/restore': typeof ApiHistoryRestoreRoute
  '/api/history/upload-status': typeof ApiHistoryUploadStatusRoute
  '/api/history': typeof ApiHistoryIndexRoute
  '/api/history/$cardId/resize-tile': typeof ApiHistoryCardIdResizeTileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/extract-master': typeof ApiExtractMasterRoute
  '/api/fetch-master': typeof ApiFetchMasterRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/me': typeof ApiMeRoute
  '/history/$cardId': typeof HistoryCardIdRoute
  '/history/': typeof HistoryIndexRoute
  '/api/admin/credits': typeof ApiAdminCreditsRoute
  '/api/admin/history': typeof ApiAdminHistoryRoute
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/pricing': typeof ApiAdminPricingRoute
  '/api/admin/role': typeof ApiAdminRoleRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/history/$cardId': typeof ApiHistoryCardIdRouteWithChildren
  '/api/history/bulk-delete': typeof ApiHistoryBulkDeleteRoute
  '/api/history/bulk-zip': typeof ApiHistoryBulkZipRoute
  '/api/history/clone-card': typeof ApiHistoryCloneCardRoute
  '/api/history/restore': typeof ApiHistoryRestoreRoute
  '/api/history/upload-status': typeof ApiHistoryUploadStatusRoute
  '/api/history/': typeof ApiHistoryIndexRoute
  '/api/history/$cardId/resize-tile': typeof ApiHistoryCardIdResizeTileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/reset-password'
    | '/api/extract-master'
    | '/api/fetch-master'
    | '/api/generate-image'
    | '/api/me'
    | '/history/$cardId'
    | '/history/'
    | '/api/admin/credits'
    | '/api/admin/history'
    | '/api/admin/logs'
    | '/api/admin/pricing'
    | '/api/admin/role'
    | '/api/admin/settings'
    | '/api/admin/users'
    | '/api/auth/change-password'
    | '/api/auth/forgot-password'
    | '/api/history/$cardId'
    | '/api/history/bulk-delete'
    | '/api/history/bulk-zip'
    | '/api/history/clone-card'
    | '/api/history/restore'
    | '/api/history/upload-status'
    | '/api/history/'
    | '/api/history/$cardId/resize-tile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/reset-password'
    | '/api/extract-master'
    | '/api/fetch-master'
    | '/api/generate-image'
    | '/api/me'
    | '/history/$cardId'
    | '/history'
    | '/api/admin/credits'
    | '/api/admin/history'
    | '/api/admin/logs'
    | '/api/admin/pricing'
    | '/api/admin/role'
    | '/api/admin/settings'
    | '/api/admin/users'
    | '/api/auth/change-password'
    | '/api/auth/forgot-password'
    | '/api/history/$cardId'
    | '/api/history/bulk-delete'
    | '/api/history/bulk-zip'
    | '/api/history/clone-card'
    | '/api/history/restore'
    | '/api/history/upload-status'
    | '/api/history'
    | '/api/history/$cardId/resize-tile'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/reset-password'
    | '/api/extract-master'
    | '/api/fetch-master'
    | '/api/generate-image'
    | '/api/me'
    | '/history/$cardId'
    | '/history/'
    | '/api/admin/credits'
    | '/api/admin/history'
    | '/api/admin/logs'
    | '/api/admin/pricing'
    | '/api/admin/role'
    | '/api/admin/settings'
    | '/api/admin/users'
    | '/api/auth/change-password'
    | '/api/auth/forgot-password'
    | '/api/history/$cardId'
    | '/api/history/bulk-delete'
    | '/api/history/bulk-zip'
    | '/api/history/clone-card'
    | '/api/history/restore'
    | '/api/history/upload-status'
    | '/api/history/'
    | '/api/history/$cardId/resize-tile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiExtractMasterRoute: typeof ApiExtractMasterRoute
  ApiFetchMasterRoute: typeof ApiFetchMasterRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiMeRoute: typeof ApiMeRoute
  HistoryCardIdRoute: typeof HistoryCardIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  ApiAdminCreditsRoute: typeof ApiAdminCreditsRoute
  ApiAdminHistoryRoute: typeof ApiAdminHistoryRoute
  ApiAdminLogsRoute: typeof ApiAdminLogsRoute
  ApiAdminPricingRoute: typeof ApiAdminPricingRoute
  ApiAdminRoleRoute: typeof ApiAdminRoleRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiHistoryCardIdRoute: typeof ApiHistoryCardIdRouteWithChildren
  ApiHistoryBulkDeleteRoute: typeof ApiHistoryBulkDeleteRoute
  ApiHistoryBulkZipRoute: typeof ApiHistoryBulkZipRoute
  ApiHistoryCloneCardRoute: typeof ApiHistoryCloneCardRoute
  ApiHistoryRestoreRoute: typeof ApiHistoryRestoreRoute
  ApiHistoryUploadStatusRoute: typeof ApiHistoryUploadStatusRoute
  ApiHistoryIndexRoute: typeof ApiHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$cardId': {
      id: '/history/$cardId'
      path: '/history/$cardId'
      fullPath: '/history/$cardId'
      preLoaderRoute: typeof HistoryCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-master': {
      id: '/api/fetch-master'
      path: '/api/fetch-master'
      fullPath: '/api/fetch-master'
      preLoaderRoute: typeof ApiFetchMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-master': {
      id: '/api/extract-master'
      path: '/api/extract-master'
      fullPath: '/api/extract-master'
      preLoaderRoute: typeof ApiExtractMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/': {
      id: '/api/history/'
      path: '/api/history'
      fullPath: '/api/history/'
      preLoaderRoute: typeof ApiHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/upload-status': {
      id: '/api/history/upload-status'
      path: '/api/history/upload-status'
      fullPath: '/api/history/upload-status'
      preLoaderRoute: typeof ApiHistoryUploadStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/restore': {
      id: '/api/history/restore'
      path: '/api/history/restore'
      fullPath: '/api/history/restore'
      preLoaderRoute: typeof ApiHistoryRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/clone-card': {
      id: '/api/history/clone-card'
      path: '/api/history/clone-card'
      fullPath: '/api/history/clone-card'
      preLoaderRoute: typeof ApiHistoryCloneCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/bulk-zip': {
      id: '/api/history/bulk-zip'
      path: '/api/history/bulk-zip'
      fullPath: '/api/history/bulk-zip'
      preLoaderRoute: typeof ApiHistoryBulkZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/bulk-delete': {
      id: '/api/history/bulk-delete'
      path: '/api/history/bulk-delete'
      fullPath: '/api/history/bulk-delete'
      preLoaderRoute: typeof ApiHistoryBulkDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/$cardId': {
      id: '/api/history/$cardId'
      path: '/api/history/$cardId'
      fullPath: '/api/history/$cardId'
      preLoaderRoute: typeof ApiHistoryCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/role': {
      id: '/api/admin/role'
      path: '/api/admin/role'
      fullPath: '/api/admin/role'
      preLoaderRoute: typeof ApiAdminRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pricing': {
      id: '/api/admin/pricing'
      path: '/api/admin/pricing'
      fullPath: '/api/admin/pricing'
      preLoaderRoute: typeof ApiAdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logs': {
      id: '/api/admin/logs'
      path: '/api/admin/logs'
      fullPath: '/api/admin/logs'
      preLoaderRoute: typeof ApiAdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/history': {
      id: '/api/admin/history'
      path: '/api/admin/history'
      fullPath: '/api/admin/history'
      preLoaderRoute: typeof ApiAdminHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/credits': {
      id: '/api/admin/credits'
      path: '/api/admin/credits'
      fullPath: '/api/admin/credits'
      preLoaderRoute: typeof ApiAdminCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/$cardId/resize-tile': {
      id: '/api/history/$cardId/resize-tile'
      path: '/resize-tile'
      fullPath: '/api/history/$cardId/resize-tile'
      preLoaderRoute: typeof ApiHistoryCardIdResizeTileRouteImport
      parentRoute: typeof ApiHistoryCardIdRoute
    }
  }
}

interface ApiHistoryCardIdRouteChildren {
  ApiHistoryCardIdResizeTileRoute: typeof ApiHistoryCardIdResizeTileRoute
}

const ApiHistoryCardIdRouteChildren: ApiHistoryCardIdRouteChildren = {
  ApiHistoryCardIdResizeTileRoute: ApiHistoryCardIdResizeTileRoute,
}

const ApiHistoryCardIdRouteWithChildren =
  ApiHistoryCardIdRoute._addFileChildren(ApiHistoryCardIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiExtractMasterRoute: ApiExtractMasterRoute,
  ApiFetchMasterRoute: ApiFetchMasterRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiMeRoute: ApiMeRoute,
  HistoryCardIdRoute: HistoryCardIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  ApiAdminCreditsRoute: ApiAdminCreditsRoute,
  ApiAdminHistoryRoute: ApiAdminHistoryRoute,
  ApiAdminLogsRoute: ApiAdminLogsRoute,
  ApiAdminPricingRoute: ApiAdminPricingRoute,
  ApiAdminRoleRoute: ApiAdminRoleRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiHistoryCardIdRoute: ApiHistoryCardIdRouteWithChildren,
  ApiHistoryBulkDeleteRoute: ApiHistoryBulkDeleteRoute,
  ApiHistoryBulkZipRoute: ApiHistoryBulkZipRoute,
  ApiHistoryCloneCardRoute: ApiHistoryCloneCardRoute,
  ApiHistoryRestoreRoute: ApiHistoryRestoreRoute,
  ApiHistoryUploadStatusRoute: ApiHistoryUploadStatusRoute,
  ApiHistoryIndexRoute: ApiHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
